# Generated by Django 5.0.4 on 2024-11-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='logo_url',
            field=models.URLField(default='https://st.adda247.com/https://currentaffairs.adda247.com/wp-content/uploads/multisite/sites/5/2024/08/28164754/NGO-Full-Form.png'),
            preserve_default=False,
        ),
    ]
