# Generated by Django 5.0.4 on 2024-11-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0002_ngo_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
