# Generated by Django 5.0.4 on 2024-11-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngos', '0003_ngo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='work_images',
            field=models.JSONField(blank=True, default=list, help_text="List of image URLs showing NGO's work"),
        ),
    ]
