version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - ganache

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "8545:8545"
    command: --deterministic --accounts 10 --host 0.0.0.0
    environment:
      - NETWORK_ID=5777

  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ngo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
