version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: django_backend
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - DB_NAME=ngo_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - ganache

  ganache:
    image: trufflesuite/ganache-cli:latest
    container_name: ganache
    ports:
      - "8545:8545"
    command: --deterministic --accounts 10 --host 0.0.0.0
    environment:
      - NETWORK_ID=5777

  db:
    image: postgres:14
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ngo_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    command: npm start
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  postgres_data:
